version: "3.1"

networks:
  kafka-net:
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
services:
  zookeeper-server:
    image: bitnami/zookeeper:latest
    networks:
      - kafka-net
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server1:
    image: bitnami/kafka:latest
    networks:
      - kafka-net
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
    volumes:
      - kafka_data:/bitnami
  kafka-magic:
    image: digitsy/kafka-magic
    networks:
      - kafka-net
    ports:
      - 9080:80
    depends_on:
      - kafka-server1
